name: ragstack-ai-assistant
services:
- name: web
  source_dir: /
  github:
    repo: Amarnathss/RAGStackGen
    branch: main
  build_command: npm run build
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: GROQ_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: JWT_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: GITHUB_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: PORT
    value: "8080"
  http_port: 8080
  routes:
  - path: /